apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: mysql
    tier: backend
spec:
  containers:
    - name: mysql
      image: ryzen28/mysql:v1
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_DATABASE
          valueFrom:
             configMapKeyRef:
               name: mysql-config
               key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
             configMapKeyRef:
               name: mysql-config
               key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
             configMapKeyRef:
               name: mysql-config
               key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             configMapKeyRef:
               name: mysql-config
               key: MYSQL_ROOT_PASSWORD
