apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
    tier: frontend
spec:
  containers:
    - name: phpmyadmin
      image: phpmyadmin
      ports:
        - containerPort: 80