apiVersion: v1 
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
    tier: frontend
spec:
  type: NodePort
  selector:
    app: phpmyadmin
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30026