apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  containers:
    - name: wordpress
      image: ryzen28/wordpress:v1
      ports:
        - containerPort: 80
      env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: WORDPRESS_DB_HOST
        - name: WORDPRESS_DB_NAME
          valueFrom:
              configMapKeyRef:
                  name: mysql-config
                  key: WORDPRESS_DB_NAME
        - name: WORDPRESS_DB_USER
          valueFrom:
              configMapKeyRef:
                  name: mysql-config
                  key: WORDPRESS_DB_USER 
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
              configMapKeyRef:
                  name: mysql-config
                  key: WORDPRESS_DB_PASSWORD
          
